<?php /* use https://github.com/dansup/bulma-templates/blob/master/templates/hero.html */ ?><!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>iten.site - Domain forwarding, Easy Setting</title>
        <link rel="shortcut icon" href="../images/fav_icon.png" type="image/x-icon">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css" />
        <link rel="stylesheet" type="text/css" href="/css/hero.css">
        <link rel="stylesheet" href="https://unpkg.com/bulma-modal-fx/dist/css/modal-fx.min.css" />
    </head>
    <body>
        <section class="hero is-info is-medium is-bold">
            <div class="hero-head">
                <nav class="navbar">
                    <div class="container">
                        <div class="navbar-brand">
                            <a class="navbar-item" href="/">
                                iten.site
                            </a>
                            <span class="navbar-burger burger" data-target="navbarMenu">
                                <span></span>
                                <span></span>
                                <span></span>
                            </span>
                        </div>
                        <div id="navbarMenu" class="navbar-menu">
                            <div class="navbar-end">
                                <div class="tabs is-right">
                                    <ul>
                                        <li class="is-active"><a>Home</a></li>
                                        <li><a href="#easy-setting">Easy Setting</a></li>
                                        <li><a href="#rest-api">Rest API</a></li>
                                        <li><a href="#hoting-yourself">Hosting Yourself</a></li>
                                    </ul>
                                    <span class="navbar-item">
                                        <a class="button is-white is-outlined" href="https://github.com/yubele/iten.site">
                                            <span class="icon">
                                                <i class="fa fa-github"></i>
                                            </span>
                                            <span title="Hello from the other side">View Source</span>
                                        </a>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
            <div class="hero-body">
                <div class="container has-text-centered">
                    <h1 class="title">
                        Redirection for Your domains.
                    </h1>
                    <h2 class="subtitle">
                        Domain transfer can be set with simple operation. 
                    </h2>
                </div>
            </div>
        </section>
        <footer class="footer">
            <div class="container">
                <div class="columns">
                    <div class="column is-3 is-offset-2">
                        <h2><strong>Media</strong></h2>
                        <ul>
                            <li><a href="https://newsdict.jp/">newsdict | みんなが気になるニュースをチェック！ニュースディクト</a></li>
                        </ul>
                    </div>
                </div>
                <div class="content has-text-centered">
                    <p>
                        <a class="icon" href="https://github.com/yubele/iten.site">
                            <i class="fa fa-github"></i>
                        </a>
                    </p>
                    <div class="control level-item">
                        <a href="https://github.com/yubele/iten.site">
                            <div class="tags has-addons">
                                <span class="tag is-dark">iten.site</span>
                                <span class="tag is-info">MIT license</span>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </footer>
    </body>
</html>